package io.github.atlascommunity.marklet;

import jdk.javadoc.doclet.Doclet;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.util.*;


import static java.lang.Boolean.parseBoolean;

/**
 * Class that reads and stores provided options for javadoc execution. Options that we care about
 * are :
 *
 * <p>* `-d` specifies the output directory (default: `javadocs`) * `-e` specifies the file ending
 * for files to be created (default `md`) * `-l` specifies the file ending used in internal links
 * (default `md`)
 *
 * <p> The default options are ideal if you want to serve the documentation using GitHub's
 * built-in README rendering. If you are using a tool like Slate, change the options as follows: ```
 * $ javadoc -doclet fr.faylixe.marklet.Marklet -e html.md -l html … ```
 */

public final class Options {

  /** Option name for the source directory. (`-i`) * */
  public static final String SOURCE_DIRECTORY_OPTION = "-i";

  /** Option name for the target output directory. (`-d`) * */
  public static final String OUTPUT_DIRECTORY_OPTION = "-d";

  /** Option name for the file ending (`-e`) * */
  public static final String FILE_ENDING_OPTION = "-e";

  /** MarkletOption name for create badge flag (`-b`) * */
  public static final String CREATE_BADGE_OPTION = "-b";


  private static final Map<String, MarkletOption> OPTIONS = new LinkedHashMap<>();

  /* Option registry **/
  static {
    OPTIONS.put(SOURCE_DIRECTORY_OPTION, new MarkletOption(
            List.of(SOURCE_DIRECTORY_OPTION),
            Doclet.Option.Kind.STANDARD,
            "directory",
            2,
            "The source directory."));

    OPTIONS.put(OUTPUT_DIRECTORY_OPTION, new MarkletOption(
            List.of(OUTPUT_DIRECTORY_OPTION),
            Doclet.Option.Kind.STANDARD,
            "directory",
            2,
            "The target output directory."));

    OPTIONS.put(FILE_ENDING_OPTION, new MarkletOption(
            List.of(FILE_ENDING_OPTION),
            Doclet.Option.Kind.STANDARD,
            "directory",
            2,
            "The file ending."));

    OPTIONS.put(CREATE_BADGE_OPTION, new MarkletOption(
            List.of(CREATE_BADGE_OPTION),
            Doclet.Option.Kind.STANDARD,
            "",
            2,
            "Create badge flag."));

  }

  /** Default output directory to use. * */
  private static final String DEFAULT_OUTPUT_DIRECTORY = "javadoc/";

  /** Default output file ending (`md`) * */
  private static final String DEFAULT_FILE_ENDING = "md";

  /** Output directory file are generated in. * */
  @Getter private final String outputDirectory;

  /** Extension to use for generated file. * */
  @Getter private final String fileEnding;

  /** Add "generated by" badge to generated doc or not. * */
  @Getter private final boolean hasBadge;

  public static MarkletOption getOption(String key) {
    if (!OPTIONS.containsKey(key)) {
      return null;
    }
    return OPTIONS.get(key);
  }

  /** Default constructor. Sets options with their default parameters if available. */
  public Options(final Map<String, String> options) {

    this.outputDirectory = options.getOrDefault(OUTPUT_DIRECTORY_OPTION, DEFAULT_OUTPUT_DIRECTORY);
    this.fileEnding = options.getOrDefault(FILE_ENDING_OPTION, DEFAULT_FILE_ENDING);
    this.hasBadge = parseBoolean(options.getOrDefault(CREATE_BADGE_OPTION, "false"));
  }

  public static Set<Doclet.Option> getSupportedOptions() {
    return new LinkedHashSet<>(OPTIONS.values());
  }
}
